- hosts: localhost
  connection: local

  tasks:
    - name: Install minimal command
      package:
        name:
          - zip
          - unzip
          # - python3
          # - python3-pip

    - name: Add Docker repository for CentOS
      shell:
        cmd: 'dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
      when: ansible_distribution == 'CentOS'

    - name: Install Docker module
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true
