- hosts: localhost
  connection: local

  tasks:
    - name: install minimal command
      package:
        name:
          - zip
          - unzip

    # - name: Add Docker repository for CentOS
    #   shell:
    #     cmd: 'dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
    #   when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux')
    - name: Add Docker repository for CentOS
      dnf:
        name: https://download.docker.com/linux/centos/docker-ce.repo
        state: present
      when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux')

    - name: Install Docker module
      package:
        name:
          - config-manager
          - docker-ce
          - docker-ce-cli

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker compose for CentOS8
      shell:
        cmd: 'pip3 install docker-compose'
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8') or ansible_distribution == 'Rocky' or ansible_distribution == 'AlmaLinux'

    - name: Install Docker compose for CentOS7
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7')
