- hosts: localhost
  connection: local

  tasks:
    - name: install minimal command
      package:
        name:
          - zip
          - unzip
          - python3

    - name: Add Docker repository for CentOS8
      shell:
        cmd: 'dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8')

    - name: Add Docker repository for CentOS7
      shell:
        cmd: 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7')
    
    - name: Install Docker module
      package:
        name:
          - docker-ce
          - docker-ce-cli

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker compose
      shell:
        cmd: 'pip3 install docker-compose'
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8')

    - name: install Software Collection (SCL)
      package:
        name:
          - centos-release-scl
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7')

    - name: Enable Software Collection (SCL) repository
      shell:
        cmd: 'yum-config-manager --enable rhel-server-rhscl-7-rpms'
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7')

    - name: install Python3.8
      package:
        name:
          - rh-python38
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7')

    # - name: Install Docker compose for CentOS7
    #   shell:
    #     cmd: 'pip install docker-compose'
    #   when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7')
    - name: Install Docker compose
      shell: |
        scl enable rh-python38 bash
        pip3 install docker-compose
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7')